'use strict';(function(){(function(){var cmpScriptElement=document.createElement('script');var firstScript=document.getElementsByTagName('script')[0];cmpScriptElement.async=true;cmpScriptElement.type='text/javascript';var cmpVersion='https://quantcast.mgr.consensu.org/tcfv2/cmp2.js';cmpScriptElement.src=cmpVersion;firstScript.parentNode.insertBefore(cmpScriptElement,firstScript);})();(function(){var css=""
+" .qc-cmp-button.qc-cmp-secondary-button:hover { "
+"   background-color: #368bd6 !important; "
+"   border-color: transparent !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button:hover { "
+"   color: #ffffff !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button { "
+"   color: #368bd6 !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button { "
+"   background-color: #eee !important; "
+"   border-color: transparent !important; "
+" } "
+""
+"";var stylesElement=document.createElement('style');var re=new RegExp('&quote;','g');css=css.replace(re,'"');stylesElement.type='text/css';if(stylesElement.styleSheet){stylesElement.styleSheet.cssText=css;}else{stylesElement.appendChild(document.createTextNode(css));}
var head=document.head||document.getElementsByTagName('head')[0];head.appendChild(stylesElement);})();var autoDetectedLanguage='en';function splitLang(lang){return lang.length>2?lang.split('-')[0]:lang;};function isSupported(lang){var langs=['bg','cs','da','de','el','en','es','et','fi','fr','ga','hr','hu','it','lt','lv','mt','nl','pl','pt','ro','sk','sl','sv'];return langs.indexOf(lang)===-1?false:true;};if(isSupported(splitLang(document.documentElement.lang))){autoDetectedLanguage=splitLang(document.documentElement.lang);}else if(isSupported(splitLang(navigator.language))){autoDetectedLanguage=splitLang(navigator.language);};var choiceMilliSeconds=(new Date).getTime();window.__tcfapi('init',2,function(){},{'premiumProperties':{'nonIabVendorListUrl':'https://quantcast.mgr.consensu.org/choice/8v2Lb-6JDpLhj/wikicat.net/.well-known/noniab-vendorlist.json'.concat('?timestamp','=',choiceMilliSeconds),},'coreUiLabels':{},'premiumUiLabels':{'uspPrivacyPolicyLinkText':'Privacy Policy',},'theme':{},'coreConfig':{'initScreenBodyTextOption':1,'consentScope':'global','lang_':autoDetectedLanguage,'defaultToggleValue':'off','displayUi':'inEU','displayPersistentConsentLink':true,'initScreenRejectButtonShowing':false,'publisherLogo':'https://cdn.wikicat.net/wp-content/uploads/2019/11/cropped-Wikicat-header-logo-small-4.png.webp','publisherPurposeIds':[1,2,3,4,5,6,7,8,9,10],'publisherPurposeLegitimateInterestIds':[],'publisherSpecialPurposesIds':[],'publisherFeaturesIds':[],'publisherSpecialFeaturesIds':[1,2],'stacks':[1,42],'rejectConsentRedirectUrl':'https://jetstudio.ch/policies/','softOptInEnabled':false,'uiLayout':'banner','vendorListUpdateFreq':30,'thirdPartyStorageType':'iframe','showSummaryView':true,'persistentConsentLinkLocation':3,'quantcastAccountId':'8v2Lb-6JDpLhj','privacyMode':["GDPR","USP"],'hashCode':'8SThjg0wsvqgRQvALOiqjw','uspVersion':1,'uspJurisdiction':["CA"],'uspLspact':'N','uspPrivacyPolicyLink':'https://jetstudio.ch/policies/','publisherName':'Wikicat','publisherCountryCode':'CH','suppressCcpaLinks':false,}});})();